diff a/modules/javafx.media/src/main/native/gstreamer/projects/win/fxplugins/Makefile b/modules/javafx.media/src/main/native/gstreamer/projects/win/fxplugins/Makefile
--- a/modules/javafx.media/src/main/native/gstreamer/projects/win/fxplugins/Makefile
+++ b/modules/javafx.media/src/main/native/gstreamer/projects/win/fxplugins/Makefile
@@ -34,11 +34,11 @@
 OBJBASE_DIR = $(BUILD_DIR)/obj/plugins
 SRCBASE_DIR = ../../../plugins
 
 GLIB_DIR        = ../../../3rd_party/glib
 GSTREAMER_DIR   = ../../../gstreamer-lite
-BASECLASSES_DIR = $(shell cygpath -mas "$(BASECLASSES_SDK_DIR)"/Samples/multimedia/directshow/baseclasses)
+BASECLASSES_DIR = ../../../3rd_party/baseclasses
 
 DIRLIST = dshowwrapper \
           javasource \
           progressbuffer \
           progressbuffer/win32
