diff a/modules/javafx.media/src/main/native/gstreamer/projects/win/glib-lite/Makefile b/modules/javafx.media/src/main/native/gstreamer/projects/win/glib-lite/Makefile
--- a/modules/javafx.media/src/main/native/gstreamer/projects/win/glib-lite/Makefile
+++ b/modules/javafx.media/src/main/native/gstreamer/projects/win/glib-lite/Makefile
@@ -30,16 +30,17 @@
               ole32.lib \
 	      Winmm.lib
 
 LDFLAGS = -out:$(shell cygpath -ma $(TARGET)) -nologo -incremental:no -libpath:$(shell cygpath -ma $(BUILD_DIR)) -dll $(SYSTEM_LIBS) \
           -manifest -manifestfile:$(MANIFEST) -manifestuac:"level='asInvoker' uiAccess='false'" \
-          -subsystem:windows -tlbid:1 -dynamicbase -nxcompat -errorreport:queue -implib:$(IMPLIB)
+          -subsystem:windows -tlbid:1 -dynamicbase -nxcompat -errorreport:queue -implib:$(IMPLIB) \
+          -def:$(DEF_DIR)/glib-lite.def
 
 ifeq ($(BUILD_TYPE), Release)
-    LDFLAGS += -def:$(DEF_DIR)/glib-lite.def -opt:ref -opt:icf
+    LDFLAGS += -opt:ref -opt:icf
 else # debug
-    LDFLAGS += -debug -def:$(DEF_DIR)/glib-liteD.def -pdb:$(shell cygpath -ma $(PDB))
+    LDFLAGS += -debug -pdb:$(shell cygpath -ma $(PDB))
 endif
 
 ifeq ($(ARCH), x32)
     LDFLAGS += -safeseh -MACHINE:x86
 else
