diff a/Makefile b/Makefile
--- a/Makefile
+++ b/Makefile
@@ -10,11 +10,11 @@
 
 build:
 	mkdir build
 
 build/%.html: src/%.md
-	pandoc $< --css guidestyle.css --strip-comments --standalone --ascii --title-prefix "The OpenJDK Developers' Guide" | iconv -f UTF-8 -t ISO-8859-1 > $@
+	pandoc $< --css guidestyle.css --strip-comments --standalone --ascii --title-prefix "The OpenJDK Developers' Guide" --include-after-body=src/footer.html | iconv -f UTF-8 -t ISO-8859-1 > $@
 	sed -i "" "/^  <meta charset=/d" $@
 
 build/guidestyle.css: build src/guidestyle.css
 	cp src/guidestyle.css build/guidestyle.css
 
