diff a/Makefile b/Makefile
--- a/Makefile
+++ b/Makefile
@@ -41,10 +41,13 @@
 	@sh gradlew clean
 
 images:
 	@sh gradlew images
 
+bots:
+	@sh gradlew :bots:cli:images
+
 install: all $(LAUNCHERS) $(MANPAGES) $(sharedir)/skara
 	@echo "Successfully installed to $(prefix)"
 
 uninstall:
 	@rm -rf $(sharedir)/skara
@@ -63,6 +66,6 @@
 $(bindir)/%: $(BUILD)/bin/%
 	@mkdir -p $(bindir)
 	@sed 's~export JAVA_HOME=.*$$~export JAVA_HOME\=$(sharedir)\/skara~' < $< > $@
 	@chmod 755 $@
 
-.PHONY: all check clean images install test uninstall
+.PHONY: all bots check clean images install test uninstall
