diff a/Makefile b/Makefile
--- a/Makefile
+++ b/Makefile
@@ -35,10 +35,16 @@
 	@sh gradlew test
 
 test:
 	@sh gradlew test
 
+clean:
+	@sh gradlew clean
+
+images:
+	@sh gradlew images
+
 install: all $(LAUNCHERS) $(MANPAGES) $(sharedir)/skara
 	@echo "Successfully installed to $(prefix)"
 
 uninstall:
 	@rm -rf $(sharedir)/skara
@@ -57,6 +63,6 @@
 $(bindir)/%: $(BUILD)/bin/%
 	@mkdir -p $(bindir)
 	@sed 's~export JAVA_HOME=.*$$~export JAVA_HOME\=$(sharedir)\/skara~' < $< > $@
 	@chmod 755 $@
 
-.PHONY: all check install test uninstall
+.PHONY: all check clean images install test uninstall
