diff a/Makefile b/Makefile
--- a/Makefile
+++ b/Makefile
@@ -10,12 +10,16 @@
 
 build:
 	mkdir build
 
 build/%.html: src/%.md
-	pandoc $< --css guidestyle.css --strip-comments --standalone --ascii --title-prefix "The OpenJDK Developers' Guide" --include-after-body=src/footer.html | iconv -f UTF-8 -t ISO-8859-1 > $@
-	sed -i "" "/^  <meta charset=/d" $@
+	cp src/footer.html build/tmp_footer.html
+	perl -pi -e 'BEGIN {$$hash=shift} s/!git-commit-hash!/$$hash/' $$(git log -1 --pretty=format:"%H" -- $<) build/tmp_footer.html
+	perl -pi -e 's;!source-file-name!;$<;' build/tmp_footer.html
+	pandoc $< --css guidestyle.css --strip-comments --standalone --ascii --to html4 --title-prefix "The OpenJDK Developers' Guide" --include-after-body=build/tmp_footer.html | iconv -f UTF-8 -t ISO-8859-1 > $@
+	perl -pi -e 's/ charset=utf-8//' $@
+	rm build/tmp_footer.html
 
 build/guidestyle.css: build src/guidestyle.css
 	cp src/guidestyle.css build/guidestyle.css
 
 build/devModel.gif: build src/devModel.gif
