diff a/modules/javafx.media/src/main/native/gstreamer/projects/mac/gstreamer-lite/Makefile b/modules/javafx.media/src/main/native/gstreamer/projects/mac/gstreamer-lite/Makefile
--- a/modules/javafx.media/src/main/native/gstreamer/projects/mac/gstreamer-lite/Makefile
+++ b/modules/javafx.media/src/main/native/gstreamer/projects/mac/gstreamer-lite/Makefile
@@ -165,10 +165,11 @@
             gst-plugins-base/gst-libs/gst/app/gstapp-marshal.c \
             gst-plugins-base/gst-libs/gst/app/gstappsink.c \
             gst-plugins-base/gst-libs/gst/audio/audio.c \
             gst-plugins-base/gst-libs/gst/audio/audio-channels.c \
             gst-plugins-base/gst-libs/gst/audio/audio-channel-mixer.c \
+	    gst-plugins-base/gst-libs/gst/audio/audio-buffer.c \
             gst-plugins-base/gst-libs/gst/audio/audio-converter.c \
             gst-plugins-base/gst-libs/gst/audio/audio-resampler.c \
             gst-plugins-base/gst-libs/gst/audio/audio-enumtypes.c \
             gst-plugins-base/gst-libs/gst/audio/audio-quantize.c \
             gst-plugins-base/gst-libs/gst/audio/audio-format.c \
