diff a/modules/javafx.media/src/main/native/gstreamer/projects/mac/glib-lite/Makefile b/modules/javafx.media/src/main/native/gstreamer/projects/mac/glib-lite/Makefile
--- a/modules/javafx.media/src/main/native/gstreamer/projects/mac/glib-lite/Makefile
+++ b/modules/javafx.media/src/main/native/gstreamer/projects/mac/glib-lite/Makefile
@@ -10,11 +10,10 @@
 OBJBASE_DIR = $(BUILD_DIR)/obj/glib-lite
 
 DIRLIST = glib \
 	  glib/libcharset/ \
 	  glib/gnulib/ \
-	  glib/pcre/ \
 	  gobject/ \
 	  gthread/ \
 	  gmodule/
 
 TARGET_NAME = lib$(BASE_NAME).dylib
@@ -28,11 +27,10 @@
          -DLIBDIR=\"/irrelevant/lib\" \
          -DG_LOG_DOMAIN=\"GLib\" \
          -DGSTREAMER_LITE \
          -DG_DISABLE_DEPRECATED \
          -DG_DISABLE_ASSERT \
-         -DPCRE_STATIC \
          -DLINK_SIZE=2 \
          -DMAX_NAME_SIZE=32 \
          -DMAX_NAME_COUNT=10000 \
          -DNEWLINE=-1 \
          -DPOSIX_MALLOC_THRESHOLD=10 \
@@ -47,11 +45,11 @@
 
 INCLUDES = -I$(SRCBASE_DIR) \
 	   -I$(SRCBASE_DIR)/glib \
 	   -I$(SRCBASE_DIR)/build/osx \
 	   -I$(LIBFFI_DIR)/include \
-	   -I$(LIBFFI_DIR)/include/x64
+	   -I$(LIBFFI_DIR)/include/mac/x64
 
 LDFLAGS += -Wl,-install_name,@rpath/$(TARGET_NAME) \
            -Wl,-framework \
            -Wl,CoreServices \
            -liconv \
@@ -98,11 +96,10 @@
             glib/gprintf.c \
             glib/gqsort.c \
             glib/gquark.c \
             glib/gqueue.c \
             glib/grand.c \
-            glib/gregex.c \
             glib/grcbox.c \
             glib/grefcount.c \
             glib/gscanner.c \
             glib/gsequence.c \
             glib/gspawn.c \
@@ -140,23 +137,10 @@
             glib/gnulib/asnprintf.c \
             glib/gnulib/printf-args.c \
             glib/gnulib/printf-parse.c \
             glib/gnulib/printf.c \
             glib/gnulib/vasnprintf.c \
-            glib/pcre/pcre_chartables.c \
-	    glib/pcre/pcre_compile.c \
-	    glib/pcre/pcre_config.c \
-	    glib/pcre/pcre_dfa_exec.c \
-	    glib/pcre/pcre_exec.c \
-	    glib/pcre/pcre_fullinfo.c \
-	    glib/pcre/pcre_get.c \
-	    glib/pcre/pcre_globals.c \
-	    glib/pcre/pcre_newline.c \
-	    glib/pcre/pcre_ord2utf8.c \
-	    glib/pcre/pcre_study.c \
-	    glib/pcre/pcre_tables.c \
-	    glib/pcre/pcre_xclass.c \
             gobject/gatomicarray.c \
             gobject/gbinding.c \
             gobject/gboxed.c \
             gobject/gclosure.c \
             gobject/genums.c \
