diff a/Makefile b/Makefile
--- a/Makefile
+++ b/Makefile
@@ -44,10 +44,16 @@
 	@sh gradlew images
 
 bots:
 	@sh gradlew :bots:cli:images
 
+offline:
+	@sh gradlew :offline
+
+reproduce:
+	@sh gradlew :reproduce
+
 install: all $(LAUNCHERS) $(MANPAGES) $(sharedir)/skara
 	@echo "Successfully installed to $(prefix)"
 
 uninstall:
 	@rm -rf $(sharedir)/skara
