diff a/modules/javafx.media/src/main/native/gstreamer/projects/mac/glib-lite/Makefile b/modules/javafx.media/src/main/native/gstreamer/projects/mac/glib-lite/Makefile
--- a/modules/javafx.media/src/main/native/gstreamer/projects/mac/glib-lite/Makefile
+++ b/modules/javafx.media/src/main/native/gstreamer/projects/mac/glib-lite/Makefile
@@ -47,11 +47,11 @@
 
 INCLUDES = -I$(SRCBASE_DIR) \
 	   -I$(SRCBASE_DIR)/glib \
 	   -I$(SRCBASE_DIR)/build/osx \
 	   -I$(LIBFFI_DIR)/include \
-	   -I$(LIBFFI_DIR)/include/x64
+	   -I$(LIBFFI_DIR)/include/mac/x64
 
 LDFLAGS += -Wl,-install_name,@rpath/$(TARGET_NAME) \
            -Wl,-framework \
            -Wl,CoreServices \
            -liconv \
