diff a/test/hotspot/jtreg/runtime/containers/docker/Dockerfile-BasicTest b/test/hotspot/jtreg/runtime/containers/docker/Dockerfile-BasicTest
--- a/test/hotspot/jtreg/runtime/containers/docker/Dockerfile-BasicTest
+++ /dev/null
@@ -1,8 +0,0 @@
-FROM oraclelinux:7.6
-MAINTAINER mikhailo.seledtsov@oracle.com
-
-COPY /jdk /jdk
-
-ENV JAVA_HOME=/jdk
-
-CMD ["/bin/bash"]
