diff a/test/hotspot/jtreg/runtime/containers/docker/Dockerfile-BasicTest-s390x b/test/hotspot/jtreg/runtime/containers/docker/Dockerfile-BasicTest-s390x
--- a/test/hotspot/jtreg/runtime/containers/docker/Dockerfile-BasicTest-s390x
+++ /dev/null
@@ -1,7 +0,0 @@
-FROM s390x/ubuntu
-
-COPY /jdk /jdk
-
-ENV JAVA_HOME=/jdk
-
-CMD ["/bin/bash"]
