diff a/test/hotspot/jtreg/runtime/containers/docker/Dockerfile-BasicTest-aarch64 b/test/hotspot/jtreg/runtime/containers/docker/Dockerfile-BasicTest-aarch64
--- a/test/hotspot/jtreg/runtime/containers/docker/Dockerfile-BasicTest-aarch64
+++ /dev/null
@@ -1,8 +0,0 @@
-# Use generic ubuntu Linux on AArch64
-FROM aarch64/ubuntu
-
-COPY /jdk /jdk
-
-ENV JAVA_HOME=/jdk
-
-CMD ["/bin/bash"]
