diff a/Makefile b/Makefile
--- a/Makefile
+++ b/Makefile
@@ -10,12 +10,12 @@
 
 build:
 	mkdir build
 
 build/%.html: src/%.md
-	pandoc $< --css guidestyle.css --strip-comments --standalone --ascii --title-prefix "The OpenJDK Developers' Guide" | iconv -f UTF-8 -t ISO-8859-1 > $@
-	sed -i "" "/^  <meta charset=/d" $@
+	pandoc $< --css guidestyle.css --strip-comments --standalone --ascii --to html4 --title-prefix "The OpenJDK Developers' Guide" | iconv -f UTF-8 -t ISO-8859-1 > $@
+	perl -pi -e 's/ charset=utf-8//' $@
 
 build/guidestyle.css: build src/guidestyle.css
 	cp src/guidestyle.css build/guidestyle.css
 
 build/devModel.gif: build src/devModel.gif
